# Generated by Django 4.2.13 on 2024-06-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0002_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('comm_long', models.FloatField()),
                ('comm_short', models.FloatField()),
                ('comm_total', models.FloatField()),
                ('comm_long_pct', models.FloatField()),
                ('comm_short_pct', models.FloatField()),
                ('comm_net_position', models.FloatField()),
                ('comm_long_change', models.FloatField()),
                ('comm_short_change', models.FloatField()),
                ('comm_net_position_change', models.FloatField()),
                ('comm_long_change_pct', models.FloatField()),
                ('comm_short_change_pct', models.FloatField()),
                ('comm_sentiment', models.CharField(max_length=50)),
                ('noncomm_long', models.FloatField()),
                ('noncomm_short', models.FloatField()),
                ('noncomm_total', models.FloatField()),
                ('noncomm_long_pct', models.FloatField()),
                ('noncomm_short_pct', models.FloatField()),
                ('noncomm_net_position', models.FloatField()),
                ('noncomm_long_change', models.FloatField()),
                ('noncomm_short_change', models.FloatField()),
                ('noncomm_net_position_change', models.FloatField()),
                ('noncomm_long_change_pct', models.FloatField()),
                ('noncomm_short_change_pct', models.FloatField()),
                ('noncomm_sentiment', models.CharField(max_length=50)),
                ('date_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahandler.dateinterval')),
            ],
        ),
    ]
