# Generated by Django 4.2.13 on 2024-06-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0003_generaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('base_long', models.FloatField()),
                ('base_short', models.FloatField()),
                ('base_net_position', models.FloatField()),
                ('quote_long', models.FloatField()),
                ('quote_short', models.FloatField()),
                ('quote_net_position', models.FloatField()),
                ('pair_long', models.FloatField()),
                ('pair_short', models.FloatField()),
                ('pair_net_position', models.FloatField()),
                ('pct_change', models.FloatField()),
                ('five_week_change', models.FloatField()),
                ('sentiment', models.CharField(max_length=20)),
                ('date_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahandler.dateinterval')),
            ],
        ),
    ]
