# Generated by Django 4.2.13 on 2024-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0008_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
