# Generated by Django 4.2.13 on 2024-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0013_recoveryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
