# Generated by Django 4.2.13 on 2024-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0014_alter_userdetails_address_alter_userdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videolinks',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
