# Generated by Django 4.2.13 on 2024-08-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0021_alter_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='position',
            field=models.TextField(blank=True, default=''),
        ),
    ]
