# Generated by Django 4.2.13 on 2024-10-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0022_userdetails_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=10)),
                ('importance', models.CharField(max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='datahandler.currency')),
            ],
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('actual', models.FloatField(null=True)),
                ('forecast', models.FloatField(null=True)),
                ('previous', models.FloatField(null=True)),
                ('surprise', models.FloatField(null=True)),
                ('trend', models.FloatField(null=True)),
                ('magnitude', models.FloatField(null=True)),
                ('score', models.FloatField(null=True)),
                ('rescaled_score', models.FloatField(null=True)),
                ('rescaled_trend', models.FloatField(null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('avg_score', models.FloatField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_data', to='datahandler.event')),
            ],
        ),
    ]
