# Generated by Django 4.2.13 on 2024-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0023_currency_event_eventdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='str_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
