# Generated by Django 4.2.13 on 2024-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0024_eventdata_str_date_alter_eventdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='rescaled_avg_score',
            field=models.FloatField(null=True),
        ),
    ]
