# Generated by Django 4.2.13 on 2024-10-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0025_eventdata_rescaled_avg_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='forecast_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='previous_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='surprise_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(max_length=255),
        ),
    ]
