# Generated by Django 4.2.13 on 2024-10-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0026_eventdata_forecast_perc_eventdata_previous_perc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='surprise_perc',
            new_name='actual_perc',
        ),
    ]
