# Generated by Django 4.2.13 on 2025-01-19 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0027_rename_surprise_perc_eventdata_actual_perc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('trend', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonalities', to='datahandler.symbol')),
            ],
            options={
                'unique_together': {('symbol', 'year', 'month')},
            },
        ),
    ]
