# Generated by Django 4.2.13 on 2025-03-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0028_symbol_seasonality'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
    ]
