# Generated by Django 4.2.13 on 2025-04-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0029_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.FloatField()),
                ('trend', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='datahandler.symbol')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
