# Generated by Django 4.2.13 on 2025-04-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0030_trends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
