# Generated by Django 4.2.13 on 2025-10-29 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0031_alter_trends_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('short_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('long_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('short_volume', models.CharField(blank=True, max_length=20, null=True)),
                ('long_volume', models.CharField(blank=True, max_length=20, null=True)),
                ('short_positions', models.CharField(blank=True, max_length=20, null=True)),
                ('long_positions', models.CharField(blank=True, max_length=20, null=True)),
                ('traders_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
