# Generated by Django 4.2.13 on 2025-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0032_sentimentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='trends',
            name='user_trend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
