# Generated by Django 4.2.13 on 2025-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0033_trends_user_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentrecord',
            name='long_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='long_positions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='long_volume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='short_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='short_positions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='short_volume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sentimentrecord',
            name='traders_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
